theme = "monokai_pro"

[editor]
line-number = "relative"
idle-timeout = 0
true-color = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

